# GraphQL schema example
#
# https://gqlgen.com/getting-started/

enum RecordCategory {
	"""
	average
	"""
	NORMAL
	"""
	set fix amount list
	"""
	FIX
	"""
	set Part to split
	"""
	PART
	"""
	after set fix money choose some address average split last money, use plus mean should engage average sharing
	"""
	FIX_BEFORE_NORMAL
	"""
	transfer money
	"""
	TRANSFER
}

type Record {
	id: ID!
	name: String
	amount: Float
	prePayAddress: Address
	"""
	time: by JS Date().getTime().toString()
	"""
	time: String!
	shouldPayAddress: [Address!]
	extendPayMsg: [Float!]
	category: RecordCategory!
	parentRecordId: ID
	isDeleted: Boolean!
	isValid: Boolean!
	isActive: Boolean!
}

type Payment {
	amount: Float!
	address: Address!
}

type Address {
	id: ID!
	name: String!
}

type Tx {
	input: [Payment!]!
	output: Payment!
}

type Trip {
	id: ID!
	name: String!
	records: [Record!]!
	moneyShare: [Tx!]!
	addresses: [Address!]!
	isValid: Boolean!
}

type Subscription {
	subRecordCreate(tripId: ID!): Record!
	subRecordUpdate(tripId: ID!): Record!
	subAddressCreate(tripId: ID!): Address!
	subAddressUpdate(tripId: ID!): Address!
	subAddressDelete(tripId: ID!): Address!
}

type Query {
	trip(tripId: ID!): Trip
}

input NewRecord {
	name: String!
	amount: Float!
	prePayAddressId: ID!
	"""
	time: by JS Date().getTime().toString()
	"""
	time: String
	shouldPayAddressIds: [ID!]!
	extendPayMsg: [Float!]
	category: RecordCategory
	isDeleted: Boolean
}

input EditRecord {
	old: NewRecord
	new: NewRecord
}

input NewTrip {
	name: String!
}

input NewAddress {
	name: String!
}

type Mutation {
	createTrip(input: NewTrip!): Trip!
	updateTrip(tripId: ID!, input: NewTrip!): Trip!
	createRecord(tripId: ID!, input: NewRecord!): Record!
	updateRecord(recordId: ID!, input: EditRecord!): Record!
	createAddress(tripId: ID!, input: NewAddress!): Address!
	updateAddress(tripId: ID!, addressId: ID!, input: NewAddress!): Address!
	deleteAddress(tripId: ID!, addressId: ID!): Address!
}
