// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTrip struct {
	Name string `json:"name"`
}

type Query struct {
}

type Subscription struct {
}

type Tx struct {
	Amount float64  `json:"amount"`
	Input  []string `json:"input"`
	Output string   `json:"output"`
}
